name: to_string_pretty
description: A starting point for Dart libraries or applications.
version: 1.1.7
repository: https://github.com/sylfreee/to_string_pretty

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
